name: Laravel CI/CD (Simulated)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - dev

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, bcmath, pdo_mysql
          coverage: none

      - name: Cache Composer Dependencies
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install Dependencies
        run: composer install --no-progress --prefer-dist --no-interaction

      - name: Copy .env.example to .env
        run: cp .env.example .env

      - name: Generate Application Key
        run: php artisan key:generate

      - name: Run Unit Tests
        run: php artisan test
        
      - name: Install Node.js dependencies
        run: npm install
    
      - name: Build Project
        run: npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: ci
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Simulated Deployment
        run: |
          echo "🚀 Starting simulated deployment..."
          sleep 3
          echo "✅ Build successfully verified!"
          echo "🧠 Imagine this pushing code to your production server..."
          echo "🎉 Deployment simulation completed!"
