name: Laravel CI/CD to Bluehost (actions-totan-in)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - dev

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Checkout code
      - name: Checkout Code
        uses: actions/checkout@v4

      # 2️⃣ Setup PHP
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, bcmath, pdo_mysql
          coverage: none

      # 3️⃣ Cache Composer dependencies
      - name: Cache Composer Dependencies
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      # 4️⃣ Install Composer dependencies
      - name: Install Dependencies
        run: composer install --no-progress --prefer-dist --no-interaction

      # 5️⃣ Copy .env safely
      - name: Copy .env.example to .env
        run: |
          if [ ! -f .env ]; then
            cp .env.example .env
          else
            echo ".env already exists, skipping copy"
          fi

      # 6️⃣ Generate application key
      - name: Generate Application Key
        run: php artisan key:generate

      # 8️⃣ Run Unit Tests
      - name: Run Unit Tests
        run: php artisan test
      # 9️⃣ Install Node dependencies
      - name: Install Node.js Dependencies
        run: npm install

      # 🔟 Build frontend/assets
      - name: Build Project
        run: npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: ci
    steps:
      # 1️⃣ Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v4

      # 2️⃣ Deploy via FTP to Bluehost
      - name: Deploy to Bluehost via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: ${{ secrets.FTP_PORT }}
          protocol: ftp
          local-dir: ./actions-totan-in/
          server-dir: /home1/ronmrhmy/public_html/action-totan-in/
          exclude: |
            **/.git*
            **/.github*
            **/node_modules/**
            **/tests/**
            **/storage/**
            **/vendor/**
            **/.env
            **/README.md
